/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class freeman_ndk_NDKUtils */

#ifndef _Included_freeman_ndk_NDKUtils
#define _Included_freeman_ndk_NDKUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     freeman_ndk_NDKUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_freeman_ndk_NDKUtils_getCLanguageString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
