/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class freeman_ndk_NDKUtils */

#ifndef _Included_freeman_ndk_NDKUtils
#define _Included_freeman_ndk_NDKUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     freeman_ndk_NDKUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_freeman_ndk_NDKUtils_getCLanguageString
  (JNIEnv *, jclass);

/*
 * Class:     freeman_ndk_NDKUtils
 * Method:    getCLanguageInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_freeman_ndk_NDKUtils_getCLanguageInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     freeman_ndk_NDKUtils
 * Method:    callCCode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_freeman_ndk_NDKUtils_callCCode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
